apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: applyengine-application-workers
  namespace: applyengine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: applyengine-application-workers
  minReplicas: 8
  maxReplicas: 80
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: applyengine-scraping-workers
  namespace: applyengine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: applyengine-scraping-workers
  minReplicas: 6
  maxReplicas: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

